modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="godweapon"
version="1.0"
displayName="God Weapon"
description="氪金萝莉风格多功能武器"
authors=["114514901"]

[[dependencies.godweapon]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.godweapon]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
